lib/api_web/cors_router.ex
defmodule ApiWeb.CORS do
  use Corsica.Router,
    origins: Application.get_env(:api, :origins, []),
    allow_credentials: Application.get_env(:api, :allow_credentials, true),
    max_age: Application.get_env(:api, :max_age, 600)

  resource("/*")

  # We can override single settings as well.
  resource("/public/*", allow_credentials: false)
end

lib/api_web/router.ex
defmodule ApiWeb.Router do
  use ApiWeb, :router
  use ApiWeb, :user_auth

  alias ApiWeb.Plug.EnsureRole

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_live_flash)
    plug(:put_root_layout, {ApiWeb.LayoutView, :root})
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(:fetch_current_user)
    plug(Smlr, enable: false)
  end

  pipeline :admin_browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_live_flash)
    plug(:put_root_layout, {ApiWeb.LayoutView, "admin.html"})
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(:fetch_current_user)
    plug(Smlr, enable: false)
  end

  pipeline :user_browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_live_flash)
    plug(:put_root_layout, {ApiWeb.LayoutView, "user.html"})
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(:fetch_current_user)
    plug(Smlr, enable: false)
  end

  pipeline :api do
    plug(:accepts, ["json"])
    plug(Smlr, enable: false)
  end

  pipeline :api_disabled do
    plug(:accepts, ["json"])
    plug(Smlr, enable: false)
  end

  pipeline :api_ignore_weight do
    plug(:accepts, ["json"])

    plug(Smlr,
      ignore_client_weight: true,
      compressors: [Smlr.Compressor.Gzip, Smlr.Compressor.Deflate, Smlr.Compressor.Brotli]
    )
  end

  pipeline :api_types do
    plug(:accepts, ["json"])

    plug(Smlr,
      all_types: false
    )
  end

  pipeline :api_cache do
    plug(:accepts, ["json"])

    plug(Smlr,
      ignore_client_weight: true,
      cache_opts: %{
        enable: true,
        timeout: :infinity,
        limit: nil
      }
    )
  end

  pipeline :user do
    plug(EnsureRole, [:admin, :user])
  end

  pipeline :admin do
    plug(EnsureRole, :admin)
  end

  ## Authentication routes

  scope "/user", ApiWeb do
    pipe_through([:browser, :redirect_if_user_is_authenticated])

    get("/register", UserRegistrationController, :new)
    post("/register", UserRegistrationController, :create)
    get("/log_in", UserSessionController, :new)
    post("/log_in", UserSessionController, :create)
    get("/reset_password", UserResetPasswordController, :new)
    post("/reset_password", UserResetPasswordController, :create)
    get("/reset_password/:token", UserResetPasswordController, :edit)
    put("/reset_password/:token", UserResetPasswordController, :update)
  end

  scope "/user", ApiWeb do
    pipe_through([:user_browser, :require_authenticated_user])

    get("/force_logout", UserSessionController, :force_logout)
    get("/log_out", UserSessionController, :delete)
    delete("/log_out", UserSessionController, :delete)
    get("/confirm", UserConfirmationController, :new)
    post("/confirm", UserConfirmationController, :create)
    get("/confirm/:token", UserConfirmationController, :confirm)
    get("/profile", UserProfileController, :edit)
    post("/profile", UserProfileController, :update)
  end

  scope "/user/settings", ApiWeb do
    pipe_through([:browser, :require_authenticated_user])

    get("/", UserSettingsController, :edit)
    put("/update_password", UserSettingsController, :update_password)
    put("/update_email", UserSettingsController, :update_email)
    get("/confirm_email/:token", UserSettingsController, :confirm_email)
  end

  scope "/home", ApiWeb do
    pipe_through([:user_browser, :require_authenticated_user])

    live("/", UserDashboardLive)
  end

  scope "/admin", ApiWeb do
    pipe_through([:admin_browser, :require_authenticated_user, :admin])

    live("/", AdminDashboardLive)
    live("/analytics", AdminDashboardAnalyticsLive)
    live("/accounts/online", AdminDashboardAccountsOnlineLive)
    live("/accounts/online/:email", AdminDashboardAccountsOnlineEmailLive)
  end

  scope "/admin", ApiWeb do
    pipe_through([:admin_browser, :require_authenticated_user, :admin])

    get("/accounts", AccountsController, :list)
    get("/profile/:email", UserProfileController, :show)
  end

  scope "/admin/settings", ApiWeb do
    pipe_through([:admin_browser, :require_authenticated_user, :admin])

    get("/", AdminSettingsController, :edit)
    put("/update_password", AdminSettingsController, :update_password)
    put("/update_email", AdminSettingsController, :update_email)
  end

  scope "/", ApiWeb do
    pipe_through([:browser])

    live("/", PageLive)
  end


  scope "/page", ApiWeb do
    pipe_through([:browser])

    get("/privacy", PageController, :privacy)
    get("/terms", PageController, :terms)
  end
  # Other scopes may use custom stacks.

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).

  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through(:browser)
      live_dashboard("/dashboard", metrics: ApiWeb.Telemetry)
    end
  end
end

lib/api_web/controllers/user_session_controller.ex
defmodule ApiWeb.UserSessionController do
  use ApiWeb, :controller

  alias Api.Accounts
  alias ApiWeb.UserAuth

  def new(conn, _params) do
    render(conn, "new.html", error_message: nil)
  end

  def create(conn, %{"user" => user_params}) do
    %{"email" => email, "password" => password} = user_params

    if user = Accounts.get_user_by_email_and_password(email, password) do
      UserAuth.log_in_user(conn, user, user_params)
    else
      render(conn, "new.html", error_message: "Invalid email or password")
    end
  end

  def delete(conn, _params) do
    conn
    |> put_flash(:info, "Logged out successfully.")
    |> UserAuth.log_out_user()
  end

  def force_logout(conn, _params) do
    conn
    |> put_flash(
      :info,
      "You were logged out. Please login again to continue using our application."
    )
    |> UserAuth.log_out_user()
  end
end

lib/api_web/views/user_session_view.ex
defmodule ApiWeb.UserSessionView do
  use ApiWeb, :view
end

lib/api_web/templates/user_session/new.html.eex
<div class="bg-gray-200 w-full min-h-screen flex items-center justify-center">
    <div class="w-full py-8">
        <div class="flex items-center justify-center space-x-2">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-16 w-16 text-primary" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14 10l-2 1m0 0l-2-1m2 1v2.5M20 7l-2 1m2-1l-2-1m2 1v2.5M14 4l-2-1-2 1M4 7l2-1M4 7l2 1M4 7v2.5M12 21l-2-1m2 1l2-1m-2 1v-2.5M6 18l-2-1v-2.5M18 18l2-1v-2.5" />
            </svg>
            <h1 class="text-3xl font-bold text-primary tracking-wider">Example.com</h1>
        </div>
        <div class="bg-white w-5/6 md:w-3/4 lg:w-2/3 xl:w-[500px] 2xl:w-[550px] mt-8 mx-auto px-16 py-8 rounded-lg shadow-2xl">

            <h2 class="text-center text-2xl font-bold tracking-wide text-gray-800">Sign In</h2>
            <p class="text-center text-sm text-gray-600 mt-2">Don't have an account yet?
                <%= link "Sign up here", to: Routes.user_registration_path(@conn, :new), class: "text-primary hover:text-primary-dark hover:underline", title: "Sign Up" %></p>

            <%= form_for @conn, Routes.user_session_path(@conn, :create), [class: "my-8 text-sm", as: :user], fn f -> %>

                <div class="flex flex-col my-4">
                    <%= label f, :email, [class: "text-gray-700"] do
                        "Email Address"
                    end %>

                    <%= email_input f, :email, [required: true, class: "mt-2 py-2 border-gray-300 focus:outline-none focus:ring-0 focus:border-gray-300 rounded text-sm text-gray-900", placeholder: "Enter your email"] %>

                </div>

                <div class="flex flex-col my-4">
                    <%= label f, :password, class: "text-gray-700" do
                      "Password"
                    end %>

                    <div
                            x-data="{ show: false }"
                            class="relative flex items-center mt-2"
                    >
                        <input
                                :type=" show ? 'text': 'password' "
                                name="user['password']"
                                id="user_password"
                                class="flex-1 py-2 pr-10 border-gray-300 focus:outline-none focus:ring-0 focus:border-gray-300 rounded text-sm text-gray-900"
                                placeholder="Enter your password"
                        >
                        <button
                                @click="show = !show"
                                type="button"
                                class="absolute right-2 bg-transparent flex items-center justify-center text-gray-700"
                        >
                            <svg x-show="!show" class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13.875 18.825A10.05 10.05 0 0112 19c-4.478 0-8.268-2.943-9.543-7a9.97 9.97 0 011.563-3.029m5.858.908a3 3 0 114.243 4.243M9.878 9.878l4.242 4.242M9.88 9.88l-3.29-3.29m7.532 7.532l3.29 3.29M3 3l3.59 3.59m0 0A9.953 9.953 0 0112 5c4.478 0 8.268 2.943 9.543 7a10.025 10.025 0 01-4.132 5.411m0 0L21 21"></path></svg>

                            <svg x-show="show" class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" style="display: none;"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"></path></svg>
                        </button>
                    </div>
                </div>

                <div class="flex items-center">
                    <input type="checkbox" name="remember_me" id="remember_me" class="mr-2 focus:ring-0 rounded">
                    <%= label f, :remember_me, class: "text-gray-700" do
                      "Password"
                    end %>
                </div>

                <div class="my-4 flex items-center justify-end space-x-4">
                    <%= link "Forgot your password?", to: Routes.user_reset_password_path(@conn, :new), class: "text-gray-700 hover:text-gray-900 hover:underline", title: "Forgot your password?" %>

                    <button class="bg-primary hover:bg-primary-dark rounded-lg px-8 py-2 text-gray-100 hover:shadow-xl transition duration-150 uppercase" data-method="get" data-to="<%= Routes.user_session_path(@conn, :new) %>" ><%= link "Sign In", to: Routes.user_session_path(@conn, :new) %></button>
                </div>
            <% end %>

            </div>
        </div>
    </div>